const typingTexts = {
  30: [
    "The quick brown fox jumps over the lazy dog near the riverbank every single morning without fail. The fox is known for its incredible speed and agility, darting through the tall grass with effortless grace. Every animal in the forest watches in silent admiration as it leaps and bounds across the open field.",
    "Coding is the art of telling a computer exactly what to do using a language it can understand and execute. Every program begins with a single line of logic, and from there it grows into something powerful and complex. The best developers write code that is not only functional but also clean, readable, and easy to maintain.",
    "Practice makes perfect and every single keystroke you type brings you one step closer to true mastery of the keyboard. The journey to becoming a fast and accurate typist is long but deeply rewarding. Consistency is the key, and those who dedicate even fifteen minutes a day will see dramatic improvement over time.",
    "The sun sets slowly behind the distant mountains, casting long golden shadows across the entire valley floor below. The sky transforms into a breathtaking canvas of orange, pink, and deep purple as the day comes to a peaceful close. Birds return to their nests and the world grows quiet in the fading warmth of the evening light.",
    "Speed and accuracy are both critically important when it comes to becoming a truly great typist in the modern world. Many beginners focus only on going fast, but without accuracy the result is a mess of errors that slows everything down. The wisest approach is to start slow, build muscle memory, and let speed develop naturally over time.",
  ],
  45: [
    "A good programmer writes code that humans can read and machines can execute without any errors whatsoever. Clean code is not just about making things work but about making them work in a way that others can understand and build upon. Every function should have a single clear purpose, every variable a meaningful name, and every module a well-defined boundary that separates concerns cleanly and logically.",
    "The internet has fundamentally transformed the way people communicate, learn, share information, and conduct business across the entire globe. It connects billions of people from every corner of the world and enables collaboration on a scale that was completely unimaginable just a few decades ago. Today a student in a small village can access the same knowledge as a professor at the world's most prestigious university, and that is truly remarkable.",
    "Typing fast is a skill that takes genuine time and real dedication to develop properly over the course of many months and years. The more you practice on a consistent daily basis, the more natural and effortless the entire process will eventually become for you. Your fingers will begin to find the keys without conscious thought, and your mind will be free to focus entirely on the ideas you are trying to express.",
    "Mountains have always inspired humans with their incredible grandeur, raw power, and deep sense of mystery throughout all of recorded history. Climbers from every corner of the world travel enormous distances and endure tremendous hardship just to stand at the summit and look out over the vast horizon stretching endlessly below them. The mountain does not care about your ambitions or your fears, it simply stands there, ancient and indifferent, waiting to be respected.",
    "Music is a universal language that transcends all national borders, cultural differences, and language barriers around the entire world. It has the extraordinary power to evoke the deepest human emotions and bring people together in ways that ordinary words alone could never hope to achieve. A single melody can carry a listener back decades in an instant, conjuring memories so vivid and powerful that they feel as real as the present moment.",
  ],
  60: [
    "The history of computing is a truly fascinating intellectual journey that spans several remarkable decades of relentless human innovation, brilliant engineering, and extraordinary scientific discovery. From the earliest primitive mechanical calculators built in the nineteenth century to the most extraordinarily powerful supercomputers of the present day, each successive generation of technology has thoughtfully and deliberately built upon the hard-won achievements and painful lessons of the generation that came before it. Today we carry more raw computing power in our pockets than was used to send the first human beings to the surface of the moon, and the pace of technological progress shows absolutely no signs of slowing down anytime in the foreseeable future.",
    "Learning to type both quickly and with exceptional accuracy is without question one of the single most valuable, practical, and widely transferable skills that any individual can possibly cultivate and refine in today's fast-paced and highly competitive digital world. Whether your daily work involves composing critically important professional emails, architecting and writing complex software systems, producing lengthy and detailed reports, or simply communicating with friends and colleagues, the fundamental ability to translate your thoughts and ideas seamlessly into written text without unnecessary friction makes you dramatically more productive and effective in virtually every area of your professional and personal life.",
    "The vast and seemingly endless ocean covers well over seventy percent of the entire surface area of our remarkable planet Earth, and yet despite centuries of determined human exploration and rigorous scientific inquiry, it remains one of the most profoundly mysterious and least thoroughly explored frontiers that modern science has ever encountered. Hidden far beneath its dark, cold, and perpetually turbulent waves lies a complete and utterly extraordinary parallel world, teeming with bizarre and remarkable creatures that have never been seen by human eyes, filled with ancient sunken shipwrecks of tremendous historical significance, and shaped by geological forces of almost incomprehensible power and scale.",
    "Artificial intelligence and its many related subfields are fundamentally reshaping entire global industries, economic systems, and human institutions at a breathtaking pace and unprecedented scale that very few experts could have accurately predicted even just a single decade ago. From genuinely revolutionary advances in healthcare diagnostics and drug discovery to the development of fully autonomous self-driving vehicles and sophisticated intelligent robotic systems, the wide-ranging applications of modern machine learning are vast, varied, and continuing to grow at an astonishing rate. As these systems become increasingly capable, society must grapple seriously with profound questions about ethics, accountability, and the long-term future of human work.",
    "Great and enduring literature possesses a truly unique and extraordinary power to transport its fortunate readers across vast distances of time, to carry them to the most distant and exotic places imaginable, and to introduce them to entirely new perspectives on the human condition that lie far beyond the comfortable boundaries of their own limited personal experience. Through the carefully crafted pages of a truly exceptional novel, we are given the rare opportunity to inhabit lives vastly different from our own, to feel emotions we might never otherwise encounter, and to develop a deep and genuine empathy for people whose circumstances and challenges are entirely foreign to us.",
  ],
};

const getTypingText = (duration) => {
  const texts = typingTexts[duration];
  return texts[Math.floor(Math.random() * texts.length)];
};

// Round texts — length and complexity increase with each round
const roundTexts = [
  // Round 1 — ~90 chars, completable in 30s
  [
    "The cat sat on the mat and looked at the sun rising over the hills.",
    "She ran fast and won the race with a big smile on her face.",
    "He packed his bag and left before the sun came up over the trees.",
    "The dog barked loud and wagged its tail at every person walking by.",
    "I like to read books and learn something new every single day.",
  ],
  // Round 2 — ~140 chars, 35s
  [
    "The quick brown fox jumps over the lazy dog by the river every morning.",
    "She opened the window and felt the cool morning breeze on her face.",
    "Learning to type well takes daily practice but the results are worth it.",
    "The children played in the park until the sky turned dark and grey.",
    "A calm mind and steady fingers are the most important tools for a fast typist.",
  ],
  // Round 3 — ~200 chars, 45s
  [
    "Coding is the art of telling a computer what to do in a language it understands. Every program begins with a single line of logic and grows from there into something powerful.",
    "Practice makes perfect and every keystroke brings you closer to mastery. The journey to becoming a fast typist is long but deeply rewarding for those who stay consistent.",
    "The sun sets slowly behind the mountains casting long golden shadows across the valley. Birds return to their nests and the world grows quiet in the fading warmth of evening.",
    "Speed and accuracy are both important when becoming a great typist. Many beginners focus only on going fast, but without accuracy the result is a mess of errors that slows everything.",
    "A good programmer writes code that humans can read and machines can execute. Clean code is not just about functionality but also about clarity and simplicity in design.",
  ],
  // Round 4 — ~300 chars, 60s
  [
    "The internet has transformed the way people communicate and share information across the globe. It connects billions of people and enables collaboration on a scale that was completely unimaginable just a few decades ago. Today a student in a small village can access the same knowledge as a professor at a top university.",
    "Typing fast is a skill that takes genuine time and dedication to develop properly. The more you practice on a consistent daily basis, the more natural and effortless the process becomes. Your fingers will begin to find the keys without conscious thought, freeing your mind to focus entirely on ideas.",
    "Mountains have always inspired humans with their grandeur and deep sense of mystery throughout history. Climbers from every corner of the world travel enormous distances just to stand at the summit and look out over the vast horizon stretching endlessly below them in every direction.",
    "Music is a universal language that transcends all national borders and cultural differences. It has the extraordinary power to evoke the deepest human emotions and bring people together in ways that ordinary words alone could never hope to achieve on their own.",
    "The history of computing spans several remarkable decades of relentless human innovation and scientific discovery. From the earliest mechanical calculators to modern supercomputers, each generation of technology has built upon the achievements and lessons of the one before it.",
  ],
  // Round 5 — ~420 chars, 80s
  [
    "Learning to type both quickly and with exceptional accuracy is one of the most valuable skills you can develop in the modern world. Whether your work involves writing emails, coding software, or producing documents, the ability to translate your thoughts into text without friction makes you dramatically more productive. The investment of time required to develop this skill pays dividends that compound over an entire lifetime of work and communication.",
    "The vast ocean covers more than seventy percent of the surface of our planet and yet remains one of the least explored frontiers known to science. Beneath its dark waves lies an extraordinary world filled with remarkable creatures, ancient shipwrecks, and geological formations that scientists are only beginning to understand. Every deep sea expedition returns with discoveries that challenge our assumptions about the nature of life itself.",
    "Artificial intelligence is reshaping entire industries at a pace that few experts could have predicted even a decade ago. From healthcare diagnostics to autonomous vehicles, the applications of machine learning are vast and growing rapidly with each passing year. As these systems become more capable, society must grapple seriously with questions about ethics, accountability, and the future of human work in an increasingly automated world.",
    "The philosophy of science is concerned with the most fundamental questions about how human beings come to know anything about the world they inhabit. What distinguishes a scientific explanation from a non-scientific one? These questions have profound practical consequences for how we make decisions about medicine, technology, and public policy in a world where the quality of our reasoning determines the quality of our outcomes.",
    "Cities are among the most extraordinary things that human beings have ever created. They are engines of culture, commerce, and innovation, places where ideas collide and combine in ways impossible in smaller communities. But they are also places of profound inequality, where the very wealthy and the very poor live within blocks of each other, separated by nearly impenetrable barriers of class and circumstance that are difficult to overcome.",
  ],
  // Round 6 — ~560 chars, 100s
  [
    "The relationship between human beings and the natural world has always been complicated, shaped by equal parts wonder and exploitation. For most of history, nature was something to be feared and conquered, a hostile force that needed to be tamed before civilization could flourish. But as our power over the natural world has grown, so too has our understanding of how deeply we depend upon it, and how fragile the systems that sustain all life on this planet truly are. The great challenge of our time is learning to live within those systems rather than extracting from them until nothing of value remains for the generations that will come after us.",
    "Writing is one of the most demanding and most rewarding intellectual activities a human being can undertake. It requires you to take the vague, shifting thoughts that float through your mind and give them a precise and permanent shape in language. This is harder than it sounds, because most of our thinking is fuzzy and full of gaps we never notice until we try to write them down. The act of writing forces clarity, and that clarity, once achieved, changes not just the page but the mind that produced it. You understand something differently after writing about it than you did before you began.",
    "The neuroscience of decision-making has revealed that the choices we make are far less rational and far more influenced by unconscious processes than most of us would like to believe. The classical model of the rational agent who carefully weighs all options bears almost no resemblance to how actual human beings make decisions in the real world. We are subject to a vast array of cognitive biases, systematic errors in reasoning that lead us to make predictable mistakes in predictable circumstances, over and over again regardless of our intelligence or level of education.",
    "The development of language in human children is one of the most remarkable phenomena in all of biology. Within the first few years of life, without formal instruction and in the face of input that is fragmentary and often ambiguous, children acquire the full grammatical structure of their native language. This includes rules so subtle and abstract that most adult speakers cannot articulate them even though they follow them perfectly in every sentence they produce. The speed and universality of language acquisition remains one of the deepest puzzles in all of cognitive science.",
    "The experience of grief is one of the most universal and least understood aspects of human life. Every culture in the world has developed rituals for mourning the dead and helping the living find their way back to a life worth living. Yet despite this universality, grief remains deeply private and individual, shaped by the particular relationship that has been lost, the circumstances of the death, and the cultural frameworks through which the bereaved understand mortality and meaning. The psychological literature has moved away from stage models toward a more nuanced understanding of grief as a dynamic and non-linear process.",
  ],
  // Round 7 — ~700 chars, 120s
  [
    "The concept of progress is so deeply embedded in the modern worldview that it is difficult to imagine thinking about history without it, yet it is a relatively recent idea that would have been largely incomprehensible to most people who lived before the eighteenth century. For the ancient Greeks and Romans, history was cyclical, moving through recurring patterns of rise and decline rather than advancing toward any particular destination. It was only with the scientific revolution and the Enlightenment that the idea of linear progress became the dominant framework through which educated people understood their place in time. This idea has been enormously productive, driving centuries of scientific and technological achievement, but it has also been the source of some of the most dangerous illusions of the modern age, leading people to assume that change is always improvement and that the future will inevitably be better than the past.",
    "The transformation of human consciousness through the development of writing is one of the most profound and least appreciated revolutions in the history of our species. Before writing, all knowledge was stored in human memory and transmitted through speech, which meant it was inherently limited by the capacity of individual minds and the reach of individual voices. Writing changed everything. It allowed knowledge to accumulate across generations without loss, to be transmitted across distances without distortion, and to be examined and revised in ways that oral tradition could never permit. It created the possibility of science, of law, of philosophy, and of all the great intellectual traditions we think of as the foundations of civilization. But it also changed the nature of thought itself, making possible new forms of abstract reasoning and new modes of self-reflection that are simply not available to minds that have never learned to read.",
    "The ecological crisis that humanity now faces is unprecedented in the history of life on Earth, not because mass extinctions have not occurred before, but because for the first time a single species is responsible for driving the crisis through its own choices and behaviors. The scale of human impact on the natural world is almost impossible to comprehend. We have altered the chemistry of the atmosphere and the ocean. We have transformed more than half of the land surface of the planet for agriculture, cities, and industry. We have driven thousands of species to extinction and pushed thousands more to the brink. We have disrupted the nitrogen and phosphorus cycles that underpin the productivity of all terrestrial ecosystems, and we have done all of this in the geological equivalent of an eyeblink. The question is not whether we have the technical capacity to address this crisis. The question is whether we have the political will and the moral imagination to use it before it is too late.",
    "The philosophy of time is one of the oldest and most persistently puzzling areas of human inquiry, touching on questions that seem simple on the surface but reveal extraordinary depths the moment you begin to examine them seriously. What is the present moment, and why does it seem to move forward rather than backward? Is the past still real in some sense, or does it cease to exist the moment it is over? Is the future already determined, waiting to be discovered, or is it genuinely open, shaped by choices that have not yet been made? These questions bear directly on how we understand free will, moral responsibility, personal identity, and the nature of causation itself. The physicist's account of time, in which past, present, and future are equally real and the flow of time is an illusion, is deeply at odds with the lived experience of time as something that moves, that passes, and that is irreversibly lost the moment it is gone.",
    "The development of language in human children is one of the most remarkable phenomena in all of biology, a process of such complexity and speed that it has puzzled linguists, psychologists, and philosophers for generations. Within the first few years of life, without formal instruction, without conscious effort, and in the face of input that is fragmentary, inconsistent, and often ambiguous, children acquire the full grammatical structure of their native language, including rules so subtle and abstract that most adult speakers cannot articulate them even though they follow them perfectly in every sentence they produce. The linguist Noam Chomsky argued that this feat is only possible because human beings are born with an innate language faculty, a universal grammar that constrains the space of possible human languages and allows children to converge on the correct grammar from the impoverished data available to them. This hypothesis remains controversial, but the phenomenon it seeks to explain is not.",
  ],
];

const getRoundText = (round) => {
  const idx = Math.min(round - 1, roundTexts.length - 1);
  const pool = roundTexts[idx];
  return pool[Math.floor(Math.random() * pool.length)];
};

// Timer in seconds per round — increases as text gets longer
const roundTimers = [30, 35, 45, 60, 80, 100, 120];

const getRoundTimer = (round) => {
  const idx = Math.min(round - 1, roundTimers.length - 1);
  return roundTimers[idx];
};

module.exports = { getTypingText, getRoundText, getRoundTimer };
